### ISSUE TITLE
Prevent iplementation clashes in ConfigResolverProvider

### ISSUE THREAD

**Issue by struberg** [microprofile/microprofile-config#20]
The current ConfigResolverProvider assumes that there is only one Microprofile-Config implementation in the classpath. If the ServiceLoader finds multiple implementations this will lead to failures.

I think we can improve this by only picking up the 'uppermost' impl we find. 
Thus a container can provide his implementation and a e.g. WAR file could even package it's own config-impl. In this case I suggest to always enforce the config impl packaged within the container.

Anything else would require reversing the ClassLoader lookup and thus needs a deeper integration anyway.

**Comment by pavolloffay** [comment]
hi @struberg why is it preferred to load config impl packaged with the container? Shouldn't the application have more control and override things if needed?
