### ISSUE TITLE
Review ConfigProvider#emptyBuilder()

### ISSUE THREAD

**Issue by struberg** [microprofile/microprofile-config#27]
After reviewing the current ConfigProvider I ask myself why we have 2 different methods to build an unmanaged Configuration via a ConfigBuilder

* ConfigBuilder getBuilder()
* ConfigBuilder getEmptyBuilder()

I'm not quite sure why we do need the later. 
It seems that a ConfigBuilder initially is empty anyway. 
There are already 2 methods addDefaultSources() and addDefaultConverters() which one can call to trigger the scanning for ConfigSources respective Converters.

Can we remove getEmptyBuilder()?

**Comment by Emily-Jiang** [comment]
no. getEmptybuilder is to get a complete empty builder with default converters, where getBuilder will get the config with the default sources and converters. I think we can remove addDefaultSources() and addDefaultConverters() as they are private to the implementation.

**Comment by struberg** [comment]
But if we leave addDefaultConverters() and addDefaultSources() then Gunnar could e.g. pick up all Converters but _not_ the ConfigSources. Would allow for much more flexibility imo. And it lets us get rid of another method.

**Comment by Emily-Jiang** [comment]
will remove addDefaultConverters() as we agreed to the impl will always add the default converters

**Comment by Emily-Jiang** [comment]
also renamed the registerConfig to setConfig
