### ISSUE TITLE
Replace Iterable<String> in Config methods with Stream<String>

### ISSUE THREAD

**Issue by gastaldi** [microprofile/microprofile-config#36]
`Stream<String>` is a much cleaner and better API to deal with Collections than Iterable itself. One could perform operations like count, filter, collect without the need to transform the Iterable into another data structure.  

ps: It's possible for the API consumer to use `StreamSupport.stream(iterable,parallel)` if desired, but that's not so intuitive

**Comment by Emily-Jiang** [comment]
Stream is not to replace collections or Iterable. It is an interface to make data operation easier and faster. As you may know, stream is a one-time user of object and can not be traversed multiple times. I think Iterable is a better choice for the interface. If the consumer wants to filter and find elements, it is very easy to use Stream api to generate a stream to operate on.

**Comment by Emily-Jiang** [comment]
Please reopen if you have further comments.
