### ISSUE TITLE
Should the groupId change later

### ISSUE THREAD

**Issue by keilw** [microprofile/microprofile-config#38]
Right now (using the correct naming conventions) the GroupId is `org.eclipse.microprofile.incubator`.
Even for all modules underneath the parent.
It makes no distinction between an incubating "config" project and others, say health-check etc. that might follow. 

That is rather uncommon for Eclipse projects and also in podlings of Apache projects I did not see them use a groupId like `org.apache.incubator` or `org.apache.incubator.tamaya` either. It's just `org.apache.tamaya`. The version number currently ends with "-incubating-SNAPSHOT" for projects like Tamaya, that qualifier or version postfix is the only thing in the Maven artifact that changes over time. Other structures like the URL or repo folder may, but not the groupId or artifactId. 

Shouldn't we stick to common Eclipse (or other) practices here? Using "-incubating-SNAPSHOT" or similar certainly coult not hurt. I believe @waynebeaton mentioned something like it, but I don't remember the group or artifactId had to change for incubating projects like UOMo https://github.com/eclipse/uomo/blob/master/pom.xml.

**Comment by Emily-Jiang** [comment]
Is io.microprofile the agreed groupid?

**Comment by keilw** [comment]
Not for 1.1 artifacts I'd say. The repositories are in the process of moving to  "https://github.com/eclipse" so there you rarely find a POM without it (@waynebeaton said you'd have to convince him otherwise if you insist, but I don't remember there was a strong reason in the Hangout not to use "org.eclipse.microprofile".

**Comment by struberg** [comment]
Werner, you have been attending the last meeting? You remember that Wayne himself even gave counter samples? One example given is EclipseLink which even ships a package with "javax.persistence" groupId if you remember.
 
The agreed solution afair was to use "org.eclipse.microprofile.*" **for now** as long as we are _not_ aiming for a standard and still are in a 'inventing' phase. 

But once we feel that we are closing in and ready to become a standard then we either approach the JCP where it would likely end up in javax.config. Or we move the packages and groupId to a vendor neutral "io.microprofile" if the JCP is not interested.

Also regarding the repositories. My understanding was that we get an own 'area' for microprofile repos. Afaiu it is on the checklist whether this is possible under the eclipse github group.

**Comment by keilw** [comment]
Of course I have. And gave multiple examples of Eclipse projects that implement standards already. Not just JCP, that is only a small fraction in fact. 
For "implementing" parts it will likely be "org.eclipse.microprofile" all the time. For any standard, we shall see who or what is willing to standardize it. Whether that's "javax.something", "org.oasis" or "io.cnf" (the "Cloud Native Foundation" where projects like Kubernetes or OpenTracing are "standardized") or something else, we shall see.

**Comment by keilw** [comment]
Btw. this ticket was primarily about the ".incubating" postfix which I don't think makes sense, it should be ".config" unless a majority wants a different postfix or keep everything in "org.eclipse.microprofile" in a "flat" structure?

**Comment by Emily-Jiang** [comment]
fixed
