### ISSUE TITLE
ParseException on the converter

### ISSUE THREAD

**Issue by Emily-Jiang** [microprofile/microprofile-config#49]
The ParseException declared on the convert method is not useful as sometimes it is difficult to work out the index to throw this exception. Besides, most of cases, an IllegalArgumentException is thrown. I suggest to add the throws IllegalArgumentException in the javadoc so that it can be decided by end users whether to deal with this exception or not.

**Comment by struberg** [comment]
Not quite sure I get what you mean.
IllegalArgumentException is also fine for me. 
The reason for replacing the own ConverterException with any existing standard exception is that we do not treat it anyway. And a user can neither. 

The real question is: If some configured value is simply wrong (e.g. '202-14-37' for a date) what can the user do? Is it worth catching this exception? Who is responsible for logging the error? Or do we just let it blow up?

My thirst thinking is that I would let it blow up and just clearly define who is responsible for logging a meaningful message IF a value cannot get converted properly.

**Comment by Emily-Jiang** [comment]
I think we should let it blow up. If the user decides to catch it, it is his choice. I tried to explain the ParseException is less useful, as it is checked exception and you cannot wrap another exception inside (see its constructors).

**Comment by struberg** [comment]
ok I see re ParseException. Missed that.

**Comment by Emily-Jiang** [comment]
Great, thanks.

**Comment by Emily-Jiang** [comment]
Fixed
