### ISSUE TITLE
Properly bundlise the api/spis and version the packages

### ISSUE THREAD

**Issue by Emily-Jiang** [microprofile/microprofile-config#51]
Version the packages and then bundlise it to be used in the OSGi environment.

**Comment by struberg** [comment]
Not sure what the empty package-info.java do provide? Do we really need them?

**Comment by Emily-Jiang** [comment]
Mark, they are for versioning api/spi packages, so that a properly versioned bundle can be generated (http://bnd.bndtools.org/chapters/920-faq.html?#packageinfo). I updated the pom to generate  a bundle instead of a jar file.

**Comment by struberg** [comment]
Don't we like to provide a single version for the whole bundle?
In my experience giving single packages an own version tends to mess up the release cycles and also the usage.

**Comment by Emily-Jiang** [comment]
no. I am talking about package versioning. I came from OSGi background and the bundle version is less important than package version. Refer to https://www.osgi.org/wp-content/uploads/SemanticVersioning.pdf for more info.

**Comment by keilw** [comment]
+1
I guess as a minimum requirement this and other Microprofile artifacts should use Apache Felix plugin. Or Tycho (https://eclipse.org/tycho/) which is not just for "visual" Eclipse plugins, any library artifact can benefit from that.

**Comment by keilw** [comment]
IC, so no plans to use Bnd or Felix right now? The version should soon be 1.0.0 or 1.0.0-SNAPSHOT though according to official talks about this module and the overall "release train".

**Comment by Emily-Jiang** [comment]
Please see the [commits ](https://github.com/microprofile/microprofile-config/commit/2745057e98dcdfb0ac5d9dbb4b029d73b637abc8) . Bnd and Felix plugin were committed to the codebase already.

**Comment by keilw** [comment]
Ok, then it was done already;-)
