### ISSUE TITLE
Review ConfigSourceProvider

### ISSUE THREAD

**Issue by Emily-Jiang** [microprofile/microprofile-config#52]
I don't think the ConfigSourceProvider is needed. It is to cover the scenario of the multiple property files of a given name. The only usage is that inside the app, there might be multiple meta-inf\microprofile-config.properties. This is the default config sources. The implementation can do it very easily without using this interface. I cannot see any other use cases need this. It can easily avoid this situation with a different config source name. I think we should remove this interface.

**Comment by struberg** [comment]
It is indeed needed IF we keep the ConfigSource discovery. 

There are many more use cases than picking up multiple property files. Basically whenever you need to 'bridge' over to another system. It would e.g. allow for bridging over to Spring-config or DeltaSpike Config. If you remove this class then I see no easy way to do so.

To give you some historic background. Originally in DeltaSpike we only allowed to register custom ConfigSources via the ConfigSourceProvider. We only introduced the 'direct' registration of ConfigSources (without any ConfigSourceProvider) a bit later. But the use case for picking up a dynamic range of ConfigSources is still valid and important.

**Comment by Emily-Jiang** [comment]
I am not convinced. I can only see the scenario of app packaged default config source with the same name. If you provide another config source, surely you should use a different file name. I don't understand what you meant by bridging. ConfigSource is sufficient for my impl and use cases. Can you write up a detailed one to explain why ConfigSource is not sufficient.

**Comment by struberg** [comment]
Again: think about having a 

```Java
public class SpringConfigSourceProvider implements ConfigSourceProvider {
  public Iterable<ConfigSource> getConfigSources(ClassLoader cl) {
    List<PropertyResolver> springPropertyResolvers = getPropertyResolversFromSpringEnvironment();
    List <ConfigSource> wrappedSpringConfigSources = wrapSpringPropertyResolvers(springPropertyResolvers);
    return wrappedSpringConfigSources;
  } 
}
```

**Comment by Emily-Jiang** [comment]
ok. I think this further. Though you have not demonstrated the classloader usage, it can be useful if the config file not called microprofile-config.properties prebaked in an app and there are multiple of them in different jars.

**Comment by hutchig** [comment]
I had assumed the method that would be called on the ClassLoader would be https://docs.oracle.com/javase/8/docs/api/java/lang/ClassLoader.html#findResources-java.lang.String- Then the URLs for multiple files of the same name could be used from there without the need of an additional method?

Secondly in terms of bridging - getting the individual sources from a remote scheme could be tricky for the user without the relative priorities being reflected faithfully by the wrapping class instances returning good values for getOrdinal() (or config_ordinal). Each of the wrapping class instances would probably need to be aware of the other sources' original intended priorities (and how their wrappers were mapping this to microprofile ordinals).

I do understand that the use case for wanting to 'import' foreign config into different priority/ordinal levels (so not via a single 'SpringConfigSource' for example) but users might benefit from/need some help with some standard mappings. For example if a foreign scheme simple exposes an ordered list - how does one split this into a 'local' scheme's equivalent of development time, deploy time and runtime config as reflected in microprofile config ordinals? Perhaps the users would just have to solve this on a case by case basis?

**Comment by struberg** [comment]
@Emily-Jiang @hutchig The ClassLoader is not always necessary but sometimes good to have. Think about the ear use case. The current TCCL is not always the correct one for each and every scenario. Especially in OSGi it might be useful to pass the BundleClassLoader in question.

> could be tricky for the user without the relative priorities being reflected faithfully 
> by the wrapping class instances returning good values for getOrdinal() (or config_ordinal). 

But that's all a matter of the ConfigSourceProvider itself. At least it IS possible that way!

> Perhaps the users would just have to solve this on a case by case basis?

Yes, such a SpringConfigSourceProvider could even have it's own config with a mapping.

Another example would be bridging over to DeltaSpike Config or Tamaya (which both have the same ordinal trick)

**Comment by hutchig** [comment]
Apologies Mark - I was unclear - I was meaning that an implementer of the API would use the findResources method (of either the standard or custom loader) in the implementation and use that to cope with multiple files of the same name, even if there was no user provided ClassLoader involved. I know this works OK.

Thank you for your other helpful comments. I can remember reading stuff like http://www.java-allandsundry.com/2015/03/netflix-archaius-properties-in-spring.html -  so that sort of use case
seems to be valid and also note "Spring Cloud has a Spring Environment Bridge so Archaius can read properties from the Spring Environment" at http://projects.spring.io/spring-cloud/docs/1.0.1/spring-cloud.html.  I am all too aware though of how feature creep/change can get in the way of getting stuff out  :-) and I reckon this sort of bridging could be done whether config sources need to be registered 1 by 1 or via a collection.

**Comment by struberg** [comment]
Yes you could also 1:1 create single ConfigSources each time. But then you would need to create a single class for each and every counterpart. And this would not be dynamic anymore. You really would need to type code each time :(

**Comment by hutchig** [comment]
Yes I can see what you mean re convenience.
Sorry to sound contrary but I have seen this work in real life with >1
registered instances of the same class - a user level custom ConfigSource
implementing class where the properties are dynamic that has a setOrdinal
decoration etc.
(This is not any comment or info on my employers plans/code etc.)

**Comment by hutchig** [comment]
...and apologies again - I can see now that you mean by 'counterpart' ... each type of foreign scheme (Sping/Archaius/Tamaya etc) - and I imagine in that case you are probably right that folks would tend to create a separate class. I should read more carefully!

**Comment by struberg** [comment]
Probably talk about this again in a hangout. Much easier to understand the different opinions and options when talking directly.

**Comment by Emily-Jiang** [comment]
I'm going to close this issue as there is still value with the proposed class.

**Comment by Emily-Jiang** [comment]
Please reopen if more discussion is to be done. I'm trying to close many discussed and resolved issues.
