### ISSUE TITLE
Clarify, if Java file headers meet (Eclipse) IP requirements

### ISSUE THREAD

**Issue by keilw** [microprofile/microprofile-config#6]
The license header of the API proposal says 
 * Copyright 2016 Microprofile.io
But "Microprofile" is not a legal entity. Therefore (given Emily contributed this on behalf of IBM) it should likely say
* Copyright (c) 2016 IBM Corporation and others.
As every Eclipse project contributed by IBM does (if the contributor was Red Hat then substitute it with Red Hat, if it's an individual like Mark I guess it also works, otherwise additional contributors are covered by "others"
It does not matter, if the code is licensed under Eclipse or Apache license, the IP should be clear, otherwise it will never be accepted by Eclipse Foundation.

**Comment by Emily-Jiang** [comment]
Thanks Werner! updated accordingly.
