### ISSUE TITLE
Inconsistent getters in Config

### ISSUE THREAD

**Issue by keilw** [microprofile/microprofile-config#7]
The `Config` interface currently has 2 major getters for config attributes.
`<T> Optional<T> getPropertyValue()`
and
`Optional<String> getString()`

This feels inconsistent. I don't have a final answer, but either it should be something like

- `getPropertyValue(), getPropertyString()` or just
-  `getValue(), getString()`
or similar. Having one called "getProperty*" while the other just says "get*" feels inconsistent.

**Comment by Emily-Jiang** [comment]
created a PR to update to getValue()
